### ISSUE TITLE
Error attempting to connect to Gateway server url 'http://jupyter-EG-93c7d122-a3b1-435f-d8f6a2d0-6584-4c1c:8888'.  Ensure gateway url is valid and the Gateway instance is running.

### ISSUE THREAD

**Issue by Practcdi** [orchest/orchest#496]
**Describe the bug**  
When we open pipeline in jupyterlab and run cell it fail to execute cell and throws following error.

`Error attempting to connect to Gateway server url 'http://jupyter-EG-93c7d122-a3b1-435f-d8f6a2d0-6584-4c1c:8888'.  Ensure gateway url is valid and the Gateway instance is running.
`

**To Reproduce**  

`Create new project -> new pipeline -> open in jupyter notebook 
`

**Screenshots**  
![image](https://user-images.githubusercontent.com/58843833/134896700-7ab6011f-5087-4c7d-8990-7472709743f5.png)

**Environment**

- elementary os (linux)

**Comment by yannickperrenet** [comment]
Thanks for opening an issue @Practcdi. 

I failed to reproduce your error sadly/luckily. Could you provide us with the output of `./orchest version --ext`? Thank you.

**Comment by ricklamers** [comment]
Another potential cause is that the environment you used has an issue.

In the project in which you get this error, which environments do you have and what are the base image and setup script of it?

You can find this information by going to “Environments” in the left side menu.

**Comment by Practcdi** [comment]
> Another potential cause is that the environment you used has an issue.
> 
> In the project in which you get this error, which environments do you have and what are the base image and setup script of it?
> 
> You can find this information by going to “Environments” in the left side menu.

Hey, 

Here are the details:-

# Os Details:
![image](https://user-images.githubusercontent.com/58843833/135087333-b2a951e5-698d-4fb4-8e98-fae9cca9836e.png)

# Orchest Enviorment details 

![image](https://user-images.githubusercontent.com/58843833/135086715-c78346b6-f498-4ba2-9ed4-214b5acc36f1.png)

![image](https://user-images.githubusercontent.com/58843833/135086878-1273736a-4371-4f33-8188-5a64c6c0fc69.png)

![image](https://user-images.githubusercontent.com/58843833/135087573-ef3760ae-c63c-42c2-95fa-b0d9ff3e38c6.png)


If you need anything else for debugging, let me know.

Thanks

**Comment by Practcdi** [comment]
> Another potential cause is that the environment you used has an issue.
> 
> In the project in which you get this error, which environments do you have and what are the base image and setup script of it?
> 
> You can find this information by going to “Environments” in the left side menu.

Here it is ,
![image](https://user-images.githubusercontent.com/58843833/135088309-4565ec62-ac56-4309-a13b-e7c0ef1eb8a2.png)

**Comment by fruttasecca** [comment]
Hi @Practcdi, thanks for reporting the issue. Orchest has a CLI command that provides a debug dump (`./orchest debug --help`), could you do the following?
- stop Orchest
- start Orchest
- reproduce the bug
- run `./orchest debug --compress` (if you feel like, add `--ext` for more extensive information that *might* include some project data)
- attach the file

If possible, could you also go into `orchest/userdir` and post the result of running `ls -la`?

Thank you :)

**Comment by ricklamers** [comment]
@fruttasecca @Practcdi feel free to re-open when the debug data has shown any issues.

**Comment by playinlife** [comment]
I also encountered this problem.

Mac OS, Orchest version: v2022.02.8

Here is the logs copied from docker console:

[D 2022-02-21 07:30:34.445 EnterpriseGatewayApp] 1: Waiting to connect to docker container. Name: '', Status: 'None', IPAddress: 'None', KernelID: '857804ca-aa5e-421f-8a9f-bd916d77e531'

[D 2022-02-21 07:30:34.957 EnterpriseGatewayApp] 2: Waiting to connect to docker container. Name: '', Status: 'None', IPAddress: 'None', KernelID: '857804ca-aa5e-421f-8a9f-bd916d77e531'

Started Jupyter kernel in normal docker mode

Traceback (most recent call last):

  File "/usr/local/share/jupyter/kernels/launch_docker.py", line 150, in <module>

    launch_docker_kernel(kernel_id, response_addr, spark_context_init_mode)

  File "/usr/local/share/jupyter/kernels/launch_docker.py", line 83, in launch_docker_kernel

    kwargs["cpu_shares"] = _config.USER_CONTAINERS_CPU_SHARES

AttributeError: module '_orchest.internals.config' has no attribute 'USER_CONTAINERS_CPU_SHARES'

[D 2022-02-21 07:30:35.466 EnterpriseGatewayApp] 3: Waiting to connect to docker container. Name: '', Status: 'None', IPAddress: 'None', KernelID: '857804ca-aa5e-421f-8a9f-bd916d77e531'

[D 2022-02-21 07:30:35.466 EnterpriseGatewayApp] response socket still open, close it

[E 2022-02-21 07:30:35.466 EnterpriseGatewayApp] Error occurred during launch of KernelID: 857804ca-aa5e-421f-8a9f-bd916d77e531.  Check Enterprise Gateway log for more information.

[E 220221 07:30:35 web:2250] 500 POST /jupyter-server-a30c3e4a-f644-4a9d-ddf4ded1-39e1-4f07/api/kernels (172.18.0.13) 1627.73ms

[I 220221 07:30:43 web:2250] 200 GET /jupyter-server-a30c3e4a-f644-4a9d-ddf4ded1-39e1-4f07/api/kernels (172.18.0.13) 1.76ms

[I 220221 07:30:53 web:2250] 200 GET /jupyter-server-a30c3e4a-f644-4a9d-ddf4ded1-39e1-4f07/api/kernels (172.18.0.13) 0.81ms

[I 220221 07:31:03 web:2250] 200 GET /jupyter-server-a30c3e4a-f644-4a9d-ddf4ded1-39e1-4f07/api/kernels (172.18.0.13) 0.80ms

[I 220221 07:31:13 web:2250] 200 GET /jupyter-server-a30c3e4a-f644-4a9d-ddf4ded1-39e1-4f07/api/kernels (172.18.0.13) 2.27ms

[D 2022-02-21 07:31:19.535 EnterpriseGatewayApp] Found kernel python3 in /opt/conda/share/jupyter/kernels

[D 2022-02-21 07:31:19.539 EnterpriseGatewayApp] Found kernel orchest-kernel-08e9d3dd-777f-4db8-b262-2d96bbe931cc in /usr/local/share/jupyter/kernels

[W 2022-02-21 07:31:19.542 EnterpriseGatewayApp] Error loading kernelspec 'python3'

    Traceback (most recent call last):

      File "/opt/conda/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 257, in get_all_specs

        spec = self._get_kernel_spec_by_name(kname, resource_dir)

      File "/opt/conda/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 200, in _get_kernel_spec_by_name

        return self.kernel_spec_class.from_resource_dir(resource_dir)

      File "/opt/conda/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 46, in from_resource_dir

        kernel_dict = json.load(f)

      File "/opt/conda/lib/python3.7/json/__init__.py", line 296, in load

        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)

      File "/opt/conda/lib/python3.7/json/__init__.py", line 348, in loads

        return _default_decoder.decode(s)

      File "/opt/conda/lib/python3.7/json/decoder.py", line 337, in decode

        obj, end = self.raw_decode(s, idx=_w(s, 0).end())

      File "/opt/conda/lib/python3.7/json/decoder.py", line 355, in raw_decode

        raise JSONDecodeError("Expecting value", s, err.value) from None

    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[I 220221 07:31:19 web:2250] 200 GET /jupyter-server-a30c3e4a-f644-4a9d-ddf4ded1-39e1-4f07/api/kernelspecs (172.18.0.13) 28.15ms

[I 220221 07:31:23 web:2250] 200 GET /jupyter-server-a30c3e4a-f644-4a9d-ddf4ded1-39e1-4f07/api/kernels (172.18.0.13) 1.00ms

[I 220221 07:31:33 web:2250] 200 GET /jupyter-server-a30c3e4a-f644-4a9d-ddf4ded1-39e1-4f07/api/kernels (172.18.0.13) 9.20ms

**Comment by fruttasecca** [comment]
Hi @playinlife, I suspect this might be related to some stale resource or Jupyter EG not being on the same version of
the rest of Orchest. Could you try to do the following and report back?

- `./orchest status --ext` (this is to verify that all Orchest images are on the same version)

**Comment by yannickperrenet** [comment]
To add to the discussion, the warning that you found in the logs of the enterprise gateway, i.e.:
```
[W 2022-02-21 07:31:19.542 EnterpriseGatewayApp] Error loading kernelspec 'python3'
```
is expected. We throw the error on purpose to ensure that only the correct kernels are shown in the JupyterLab UI.

**Comment by playinlife** [comment]
> Hi @playinlife, I suspect this might be related to some stale resource or Jupyter EG not being on the same version of the rest of Orchest services. Could you try to do the following and report back?
> 
> `./orchest status --ext` (this is to verify that all Orchest images are on the same version)

The output:

Orchest is running.
Performing extensive status checks...
All services are ready.

**Comment by yannickperrenet** [comment]
Awesome thank you.

I think @fruttasecca meant to propose `./orchest version --ext`. But the output you just provided is helpful as well ;)

Could you share that output as well?

**Comment by playinlife** [comment]
> Awesome thank you.
> 
> I think @fruttasecca meant to propose `./orchest version --ext`. But the output you just provided is helpful as well ;)
> 
> Could you share that output as well?

Maybe that's the problem. 

`./orchest version --ext`

--------------------------------------------------------
Getting versions of all containers...
orchest/jupyter-enterprise-gateway:latest   : v2021.06.3
orchest/jupyter-server:latest               : v2022.02.8
orchest/memory-server:latest                : v2022.02.8
orchest/session-sidecar:latest              : v2022.02.8
orchest/update-server:latest                : v2022.02.8
orchest/orchest-api:latest                  : v2022.02.8
orchest/orchest-webserver:latest            : v2022.02.8
orchest/celery-worker:latest                : v2021.12.0
orchest/auth-server:latest                  : v2022.02.8
orchest/file-manager:latest                 : v2021.12.0
orchest/nginx-proxy:latest                  : v2021.10.2
orchest/base-kernel-py:latest               : v2022.02.8
Not all containers are running on the same version of Orchest, which can
lead to the application crashing. You can fix this by running:
        orchest update
This should get all containers on the same version again.
---------------------------------------------------------

when I execute the `orchest update` command, the output is:
---------------------------------------------------------
a2abf6c4d29d: Already exists 
625294dad115: Already exists 
08df3e6c0bde: Already exists 
7e941b2681b0: Already exists 
8ca822cf3e83: Already exists 
6b4068fee5bc: Pulling fs layer 
a829d9de7975: Pulling fs layer 
cf06f858f31b: Pulling fs layer 
246ea73fe963: Waiting 
latest: Pulling from orchest/orchest-ctl
Digest: sha256:0fe692824299cc00839b5efab97b0a520fc4120d1564d3e892b5ae70b7eae847
Status: Image is up to date for orchest/orchest-ctl:latest
docker.io/orchest/orchest-ctl:latest
Updating...
Cancelling update...
Make sure you have the master branch checked out before updating.
ERROR: Failed update due to master branch not being checked out.
------------------------------------------------------------
should i use a released version?

**Comment by fruttasecca** [comment]
Seems like we are getting closer to the issue.

Could you verify what kind of changes have been done to the repo? Essentially, the current update process checks out master to use the latest version of some scripts, and it will cancel the update process if that means, potentially, conflicting with some changes that have been done to the repo.

My guess is that if you stash the changes and run the update again everything should be fixed.

**Comment by yannickperrenet** [comment]
> My guess is that if you stash the changes and run the update again everything should be fixed.

I agree. 

And thanks @playinlife for all the outputs :100:

**Comment by playinlife** [comment]
> > I think @fruttasecca meant to propose ./orchest version --ext. But the output you just provided is helpful as well ;)
> 
> Definitively, sorry :)).
> 
> Seems like we are getting closer to the issue.
> 
> Could you verify what kind of changes have been done to the repo? Essentially, the current update process checks out master to use the latest version of some scripts, and it will cancel the update process if that means, potentially, conflicting with some changes that have been done to the repo.
> 
> My guess is that if you stash the changes and run the update again everything should be fixed.

I create a new folder and git clone the master branch to the new folder,  so the new repo should have no changes. Then execute `orchest update` and get the same  ERROR. 
I suspect if the registry-mirrors is not synchronized, however, after I update the registry-mirrors, still not OK.

latest: Pulling from orchest/orchest-ctl
Digest: sha256:0fe692824299cc00839b5efab97b0a520fc4120d1564d3e892b5ae70b7eae847
Status: Image is up to date for orchest/orchest-ctl:latest
docker.io/orchest/orchest-ctl:latest
Updating...
Cancelling update...
It seems like you have unstaged changes in the 'orchest' repository.
Please commit or stash them as 'orchest update' pulls the newest changes
to the 'userdir/' using a rebase.
ERROR: Failed update due to unstaged changes.

**Comment by fruttasecca** [comment]
That's very strange. Could you report the output of `git status` and/or `git diff`  of the new repo? Thank you for bearing with us :).

**Comment by playinlife** [comment]
> 
`git status`
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

`git diff`
No output.

**Comment by yannickperrenet** [comment]
As a (temporary) workaround you could run `./orchest update --dev`. This will skip the repository update which shouldn't be needed in this case and resume the regular update process.

**Comment by yannickperrenet** [comment]
If the suggested workaround solves it, could you share the output of `ls -aln` inside the `orchest` repository? Thanks.

**Comment by playinlife** [comment]
`./orchest update --dev`

Updating...
Pulling images: 14/14|#################################################|
Checking whether all containers are running the same version of Orchest.
Getting versions of all containers...
orchest/jupyter-enterprise-gateway:latest   : v2021.06.3
orchest/jupyter-server:latest               : v2022.02.9
orchest/memory-server:latest                : v2022.02.8
orchest/session-sidecar:latest              : v2022.02.8
orchest/update-server:latest                : v2021.10.2
orchest/orchest-api:latest                  : v2021.10.2
orchest/orchest-webserver:latest            : v2022.02.9
orchest/celery-worker:latest                : v2021.12.0
orchest/auth-server:latest                  : v2022.02.9
orchest/file-manager:latest                 : v2021.12.0
orchest/nginx-proxy:latest                  : v2021.10.2
orchest/base-kernel-py:latest               : v2022.02.8
Not all containers are running on the same version of Orchest, which can
lead to the application crashing. You can fix this by running:
        orchest update
This should get all containers on the same version again.
Update was unsuccessful.
Orchest was unable to pull the latest version of its currently pulled
images. Please make sure you have enough disk space available. Or if you
have plently of disk space available, try updating again later (~30
minutes should work).


The disk still has 86G of remaining space, and after started, the situation is still the same.

`ls -aln` output:
total 760
drwxr-xr-x  30 501  20     960  2 23 10:56 .
drwxr-xr-x@  4 501  20     128  2 21 18:22 ..
-rw-r--r--@  1 501  20    8196  2 22 10:16 .DS_Store
-rw-r--r--   1 501  20     214  2 21 18:22 .dockerignore
-rw-r--r--   1 501  20     999  2 21 18:22 .eslintrc.js
-rw-r--r--   1 501  20     469  2 21 18:22 .flake8
drwxr-xr-x  16 501  20     512  2 23 15:20 .git
-rw-r--r--   1 501  20      14  2 21 18:22 .gitattributes
drwxr-xr-x   9 501  20     288  2 21 18:23 .github
-rw-r--r--   1 501  20    2375  2 21 18:22 .gitignore
-rw-r--r--   1 501  20       7  2 21 18:22 .nvmrc
-rw-r--r--   1 501  20    1265  2 21 18:22 .pre-commit-config.yaml
-rw-r--r--   1 501  20      65  2 21 18:22 .prettierignore
-rw-r--r--   1 501  20      80  2 21 18:22 .prettierrc.js
-rw-r--r--   1 501  20     255  2 21 18:22 .readthedocs.yaml
-rw-r--r--@  1 501  20   34523  2 21 18:22 LICENSE
-rw-r--r--@  1 501  20    7723  2 21 18:22 README.md
drwxr-xr-x@  7 501  20     224  2 21 18:22 cypress
drwxr-xr-x@  6 501  20     192  2 21 18:22 docs
drwxr-xr-x@  6 501  20     192  2 21 18:23 lib
-rwxr-xr-x@  1 501  20    2480  2 21 18:22 orchest
drwxr-xr-x@  5 501  20     160  2 21 18:22 orchest-sdk
-rw-r--r--@  1 501  20    1266  2 21 18:22 package.json
-rw-r--r--   1 501  20  269838  2 23 10:56 pnpm-lock.yaml
-rw-r--r--@  1 501  20     145  2 21 18:22 pnpm-workspace.yaml
-rw-r--r--@  1 501  20     457  2 21 18:22 pyproject.toml
drwxr-xr-x@ 12 501  20     384  2 21 18:22 scripts
drwxr-xr-x@ 16 501  20     512  2 21 18:23 services
-rw-r--r--@  1 501  20     407  2 21 18:22 tsconfig.json
drwxr-sr-x   9 501  20     288  2 22 10:16 userdir

**Comment by fruttasecca** [comment]
@playinlife a bit of a shot in the dark, any chance that you are on docker for mac and the disk image size needs to be increased?
See https://docs.docker.com/desktop/mac/space/

We are still looking into it

**Comment by playinlife** [comment]
Disk image size default is 59.6GB, now increased to 128GB, still prompt the same message.

Docker: Disk image size 128 GB (21.8 GB used)

Macintosh HD: 78.3G available

**Comment by yannickperrenet** [comment]
When running `./orchest update --dev` pretty much the only thing we are doing is pulling the latest Docker image from our registry on Docker Hub. The output you are seeing indicates that some images fail to pull, leaving them on older versions.

Could you try to pull some images directly and see whether that works? For example:
```bash
docker pull orchest/jupyter-enterprise-gateway:latest
```

Lastly, the output of `docker info` could be useful. I am not exactly sure why the update is failing, but I guess it has something to do with Docker.

**Comment by fruttasecca** [comment]
I would also try docker system df

**Comment by playinlife** [comment]
Maybe it's my network's problem, I have tried several times from scratch, including delete all the other images, reset docker and disk config,  update docker to the latest version, get the new git code, etc. it seems that I can not get all the images with the same version. 
I will try later.

**Comment by yannickperrenet** [comment]
Sorry to hear that the issue didn't resolve itself when doing a clean install. For the time being, feel free to request a free instance at https://cloud.orchest.io/signup.

**Comment by yannickperrenet** [comment]
@playinlife Did you find out whether it indeed was a network problem?

**Comment by huangkai31** [comment]
solved by build images . I also got the same problem  #757 
and run the following solved the problem
```

git checkout v2022.03.0
scripts/build_container.sh
```

After that, check the version and I got
```
Getting versions of all containers...
orchest/jupyter-enterprise-gateway:latest   : v2022.03.0
orchest/jupyter-server:latest               : v2022.03.0
orchest/memory-server:latest                : v2022.03.0
orchest/session-sidecar:latest              : v2022.03.0
orchest/update-server:latest                : v2022.03.0
orchest/orchest-api:latest                  : v2022.03.0
orchest/orchest-webserver:latest            : v2022.03.0
orchest/celery-worker:latest                : v2022.03.0
orchest/auth-server:latest                  : v2022.03.0
orchest/file-manager:latest                 : v2022.03.0
orchest/nginx-proxy:latest                  : v2022.03.0
orchest/base-kernel-py:latest               : v2022.03.0
orchest/base-kernel-r:latest                : v2022.03.0
```

**Comment by playinlife** [comment]
> Fixed #757 solved by build images . I also got the same problem #757 and run the following solved the problem
> 
> ```
> 
> git checkout v2022.03.0
> scripts/build_container.sh
> ```
> 
> After that, check the version and I got
> 
> ```
> Getting versions of all containers...
> orchest/jupyter-enterprise-gateway:latest   : v2022.03.0
> orchest/jupyter-server:latest               : v2022.03.0
> orchest/memory-server:latest                : v2022.03.0
> orchest/session-sidecar:latest              : v2022.03.0
> orchest/update-server:latest                : v2022.03.0
> orchest/orchest-api:latest                  : v2022.03.0
> orchest/orchest-webserver:latest            : v2022.03.0
> orchest/celery-worker:latest                : v2022.03.0
> orchest/auth-server:latest                  : v2022.03.0
> orchest/file-manager:latest                 : v2022.03.0
> orchest/nginx-proxy:latest                  : v2022.03.0
> orchest/base-kernel-py:latest               : v2022.03.0
> orchest/base-kernel-r:latest                : v2022.03.0
> ```

Yes, follow your steps, the problem is solved! @huangkai31 

So it doesn't look like a network problem. @yannickperrenet 

Thanks all. @fruttasecca @yannickperrenet @huangkai31

**Comment by yannickperrenet** [comment]
Glad everything is resolved @playinlife!

Curious though why this solved your issue, since building requires a network connection for pulling in the required dependencies (e.g. `pip install ...`) and so does installing Orchest by pulling in the images from DockerHub. Not sure whether Docker makes a difference between pulling images (from a settings perspective, e.g. max disk usage) and building the image (build cache). 

For future reference:
> Docker: Disk image size 128 GB (21.8 GB used)
> Macintosh HD: 78.3G available
